config/routes.rb
Rails.application.routes.draw do
  root "properties#index"
  get "serch", to: "properties#profile"
  get "search", to: "properties#index"

  resources :properties do
    get :archive, on: :member
    get :approve_listing, on: :member
    collection do
      get :archived, action: :index
      get :pending_listings, action: :index
      get :unapproved_listings, action: :index
      get :current_listings, action: :index
      get :profile
    end
  end

  resources :users, only: :index do
    collection do
      get :main
      get :home
      get :about
      get :contact
    end
  end

  devise_for :users, controllers: { sessions: "sessions" }
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many_attached :picture
  #before_save :approved_property
  # validates :appartment_name,:price, presence: true
  # validates :bathrooms, comparison: { greater_than_or_equal_to: 0 }
  # validates :bedrooms, comparison: { greater_than_or_equal_to: 0}
  # validates :price, comparison: { greater_than: 0}

  scope :approved, -> { where(approved: true) }
  scope :unapproved, -> { where(approved: false) }

  def self.active
    where(status: "active")
  end

  def self.archived
    where(status: "archived")
  end

  def active?
    status == "active"
  end

  def archived?
    status == "archived"
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[ show edit update destroy action approve_listing archive ]

  def index
    if request.path == root_path || request.path == archived_properties_path || request.path == search_path || request.path == unapproved_listings_properties_path || request.path == pending_listings_properties_path
      properties = if params[:q].present? && request.path == serch_path
          current_user.properties.where("appartment_name LIKE ? ", "%#{params[:q]}%")
        elsif params[:q].present? || request.path == search_path
          Property.approved.where("appartment_name LIKE ? ", "%#{params[:q]}%")
        elsif request.path == properties_path
          current_user.properties
        elsif request.path == pending_listings_properties_path
          Property.unapproved
        elsif request.path == unapproved_listings_properties_path
          current_user.properties.unapproved
        elsif request.path == current_listings_properties_path
          current_user.properties.approved
        elsif request.path == root_path
          Property.approved
        elsif request.path == archived_properties_path
          Property.archived
        end
      @pagy, @properties = pagy(properties)
    else
      @q = current_user.properties.approved.ransack(params[:q])
      @pagy, @properties = pagy(@q.result(distinct: true))
    end
  end

  def show
    authorize! :show, @property
  end

  def upload
    uploaded_file = params[:image]
    File.open(Rails.root.join("public", "uploads", uploaded_file.original_filename), "wb") do |file|
      file.write(uploaded_file.read)
    end
  end

  def new
    @property = current_user.properties.new
  end

  def profile
    @property = current_user.properties
    if params[:q].present?
      @property = current_user.properties.where("appartment_name LIKE ? ", "%#{params[:q]}%")
    end
  end

  def approve_listing
    respond_to do |format|
      if @property.update(approved: true)
        format.html { redirect_to pending_listings_properties_url, notice: "Property was successfully updated." }
        format.json { render :action, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  def archive
    respond_to do |format|
      if @property.update(status: "archived")
        format.html { redirect_to archived_properties_path, notice: "Property was successfully Archieved " }
        format.json { render :action, status: :ok, location: @property }
      end
    end
  end

  def edit
    authorize! :update, @property
  end

  def create
    @property = current_user.properties.new(property_params)

    if current_user.has_role? :admin
      @property.approved = true
    end

    respond_to do |format|
      if @property.save
        # format.turbo_stream do
        #   render turbo_stream: turbo_stream.append(:properties, partial: "properties/property",
        #     locals: { property: property })
        #   end
        format.html { redirect_to property_url(@property), notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @property.update(property_params)
        render turbo_stream: [
          turbo_stream.update(properties_url(@properties)),
        ]
        # format.html { redirect_to  property_url(@property), notice: "Property was successfully updated." }
        # format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize! :update, @property
    @property.destroy
    if request.path == archived_properties_path
      respond_to do |format|
        format.html { redirect_to root_path, notice: "Property was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to root_path, notice: "Property was successfully destroyed." }
        format.json { head :no_content }
      end
    end
    # render turbo_stream: [
    #   turbo_stream.remove(@properties),
    # ]
  end

  private

  def set_property
    @property = Property.find(params[:id])
  end

  def property_params
    params.require(:property).permit(:appartment_name, :construction_status, :bedrooms, :bathrooms, :price, :listed_by, :parking, :garden, :user_id, picture: [])
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_with(model: property) do |form| %>
  <% if property.errors.any? %>
    <div style="color: red"    class="mb-3">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :appartment_name, style: "display: block" %>
    <%= form.text_field :appartment_name %>
  </div>

  <div>
    <%= form.label :construction_status, style: "display: block" %>
    <%= form.text_field :construction_status %>
  </div>

  <div>
    <%= form.label :bedrooms, style: "display: block" %>
    <%= form.number_field :bedrooms %>
  </div>

  <div>
    <%= form.label :bathrooms, style: "display: block" %>
    <%= form.number_field :bathrooms %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :listed_by, style: "display: block" %>
    <%= form.select :listed_by, [[ " User "], ["Admin"]] %>
  </div>

  <div>
    <%= form.label :parking, style: "display: block" %>
    <%= form.text_field :parking %>
  </div>

  <div>
    <%= form.label :garden, style: "display: block" %>
    <%= form.text_field :garden %>
  </div>

   <div>
    <%= form.label :picture, style: "display: block" %>
    <%= form.file_field :picture, multiple: true %>
   </div>
  </br>
  
  <div>
    <%= form.submit %>
  </div>
  <br>
 
<% end %>

app/views/properties/_profile.html.erb
<% if request.path == unapproved_listings_properties_path || current_listings_properties_path || users_path %> 
  <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist" style="gap:20px">
    <li class="nav-item" role="presentation">
      <button  data-bs-toggle="pill" data-bs-target="#pills-home"  role="tab" aria-controls="pills-home" aria-selected="true" style="height:50px; border-radius:10px; margin-left:10px">

      <% if users_path == request.path || profile_properties_path == request.path %>
        <% is_active = 'active'  %>
        <% color = 'white'  %> 
      <% else %>
        <% is_active = ''  %>
        <% color = 'black'  %>
      <% end %>
      <%= link_to 'Profile' , users_path, style:"color:#{color}",class:"nav-link #{is_active}", id:"pills-home-tab", type:"button"  %> 
      </button>
    </li>
    <li role="presentation">
      <button id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false", style="display:flex; height:50px; border-radius:10px"> 
        <% if current_user.has_role? :admin %>
            <%#  is_active = pending_listings_properties_path == request.path %>
              <%# if is_active.eql? true  &&%>
            <% if pending_listings_properties_path == request.path %>
              <% is_active = 'active'  %>
              <% color = 'white'  %>
              <% path = pending_listings_properties_path %>  
            <% else  %>
              <% is_active = ''  %>
              <% color = 'black'  %>
              <% path = unapproved_listings_properties_path %>
            <% end %>
            <%= link_to 'Pending listing', pending_listings_properties_path, style:"color:#{color};margin-top:2px",  class:"nav-link #{is_active}"  %>
            <span style="color: #{color};background-color:green; height:70%; width:30px; border-radius:50px; align-items: center; margin-top:5px; margin-left:5px;line-height: 2.0;"><%= Property.unapproved.count%>  </span>   
        <% else %>
          <% if unapproved_listings_properties_path == request.path %>
            <% is_active = 'active'  %>
            <% color = 'white'  %>
            <% path = pending_listings_properties_path %>       
          <% else %>
            <% is_active = ''  %>
            <% color = 'black'  %>
            <% path = unapproved_listings_properties_path %>
          <% end %>
          <%= link_to 'Unapproved listing', unapproved_listings_properties_path, style:"color:#{color};margin-top:2px", class:"nav-link #{is_active}"  %>
          <span style="color:white;background-color:green; height:70%; width:30px; border-radius:50px; align-items: center; margin-top:5px; margin-left:5px;line-height: 2.0;"><%= current_user.properties.unapproved.count %>  </span>             
        <% end %>
      </button>
    </li>
    <li class="nav-item" role="presentation">
      <button  id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-contact" type="button" role="tab" aria-controls="pills-contact" aria-selected="false", style="display:flex; height:50px; border-radius:10px">
      <% if current_listings_properties_path == request.path %>
        <% is_active = 'active'  %>
        <% color = 'white'  %>           
      <% else %>
        <% is_active = ''  %>
        <% color = 'black'  %>
      <% end %>

      <%= link_to 'My Listing' , current_listings_properties_path , style:"color:#{color}; margin-top:2px" ,  class:"nav-link #{is_active}"  %><span style="color:white; background-color:black; height:70%; width:30px; border-radius:50px; align-items: center; margin-top:5px; margin-left:5px;line-height: 2.0;" > <%= current_user.properties.approved.count %> </span>
      
      </button>
    </li>
  </ul>
  <div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
   <% if profile_properties_path== request.path %>
      <% if user_signed_in? %>
      <div  class="nav-link active" style="border:1px solid black;text-align: center;width: 50%;background-color: white;"><br>
        <table border="solid black" style="text-align:center;">
          <%= image_tag current_user.image if current_user.image.attached? %>
          Name : <strong><%= current_user.name %></strong><br>
          Email : <strong><%= current_user.email %> </strong></br>
          Pincode : <strong><%= current_user.pincode %></strong><br>
          Mobile_no : <strong><%= current_user.mobile_no %></strong> 
        </table> 
        <br> 
      <% end %>
    <span> <%= link_to 'Edit profile' , edit_user_registration_path, :class => 'navbar-link' %></span>
  <% end %>
  </div>
    </div>
    <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
    </div>
    <div class="tab-pane fade" id="pills-contact" role="tabpanel"  aria-labelledby="pills-contact-tab">
    </div>
  </div>
<%end%>

app/views/properties/_property.html.erb
<div id="<%= dom_id property %>" >
<%= turbo_frame_tag dom_id(property) do %>
    <table style="border: solid; padding: 20px; margin-left: 0%; width: 45%; background-color:white;"> 
      <% property.picture.each do |picture|%>
          <td><%=   image_tag(picture, style: "height:150px; width:150px") %></td>
      <% end %>
      <tr>
        <% if root_path==request.path%>
        <th>Appartment_Name :</th>
        <td><%= property.appartment_name %></td>
        <th>Bedrooms :</th>
        <td> <%= property.bedrooms %></td>
      </tr>
      <th>Price :</th>
      <td> <b style="color:blue"><%=property.price %></b></td>
      <% else %>
        <tr>
          <th>Appartment_Name :</th>
          <td><%= property.appartment_name %></td>
          <th>Bedrooms :</th>
          <td> <%= property.bedrooms %></td>
        </tr>
        <tr>
            <th>Construction_Status :</th>
            <td><%=property.construction_status %></td>
            <th>Bathrooms :</th>
            <td><%=property.bathrooms %></td>
        </tr>
        <tr>
          <th>listed_by :</th>
          <td><%=property.listed_by %></td>
          <th>Parking :</th>
          <td><%=property.parking %></td>
        </tr>
        <tr>
          <th>Garden :</th>
          <td> <%=property.garden %></td>
          <th>Price :</th>
          <td> <b style="color:blue"><%=property.price %></b></td>
        </tr>
      <%end%>
    </table> 
<%end%>
  

app/views/properties/_search_form.html.erb
<div style="display:flex; justify-content:center">

<%= search_form_for @q do |f| %>
  <%= f.search_field :appartment_name_cont, value:'' ,class:"form-control me-2", style:"display:initial; width:auto" %>
  <%= f.submit "search", class:"btn btn-outline-success"%>
  <%= link_to 'reset', request.path, class:'cancel-button', style:"border:2px solid black;background-color:red;color:white" %>
<%end%>
</div>

app/views/properties/edit.html.erb
<h1>Editing property</h1>
 <%= turbo_frame_tag dom_id(@property) do %>
  <%= render "form", property: @property %>
 <% end %>
<br>

<div>
  <%= link_to "Show this property", @property %> |
  <%= link_to "Back to properties", properties_path %>
</div>

app/views/properties/index.html.erb
<b><%#== pagy_nav(@pagy) %></b>

<p style="color: green"><%= notice %></p>
<%if request.path !=root_path && request.path !=search_path %>
  &nbsp;<%= link_to 'Back to properties', root_path ,class:"btn btn-secondary"%><br><br>
<% end %>

<% if request.path == archived_properties_path%>
  <h1 style="color:green;background-color:white;"><b><u>Archieved properties</u></b></h1>
<% elsif request.path ==root_path || request.path == search_path %>
  <span style="border:1px solid black; font-size: 40px; background-color:black;color :white;">ALL LISTING OF PROPERTIES</span>
  <br><br>
<%elsif request.path == pending_listings_properties_path  %>
  <h1 style="color:green;background-color:white;"><b><u>Pending Listing</u></b></h1>
<% elsif user_signed_in? && current_user.has_role?(:admin)  %>
  <h1 style="color:green;background-color:white;"><b><u>Admin Listing</u></b></h1>
<% elsif user_signed_in? && request.path==unapproved_listings_properties_path %>
    <h1 style="color:green;background-color:white;"><b><u>unapproved Listing</u></b></h1>
<% else %>
  <%= render 'search_form' %>
  <h1 style="color:green;background-color:yellow  ;width:25%;"><b><u>Listing</u></b></h1>
  <br>
<%end%>

<div id="properties" >
  <% @properties.each do |property| %> 
    <%= render property %>
    <p>
       <%= link_to "Show more", property, class:"btn btn-info"  %>
       <% if property.active? %>
        <%= link_to 'Archive', archive_property_path(property),  class:"btn btn-warning" %>
       <% end %>
       <% if can? :update, property %>
         <%= link_to "Edit properties", edit_property_path(property), class:"btn btn-primary" %>
       <% end %> 
       <% if can? :destroy, property %>
         <%= button_to "Destroy this property", property_path(property), method: :delete, class:"btn btn-danger"  %>
       <% end %>
       <%if request.path == pending_listings_properties_path  %>
        <%= link_to "Approve", approve_listing_property_path(property), class:"btn btn-success" %>
       <% end %>
    </p>
    <hr style="border: 5px solid black;">
  <% end %>
</div>

app/views/properties/new.html.erb
<ul><h1>New property</h1>
<%= render "form", property: @property %>
<br>
<div>
<%= link_to 'Back to properties',  root_path %>
</div>

app/views/properties/profile.html.erb
<%#= image_tag 'as.jpg', alt: 'icon' %>

app/views/properties/show.html.erb
<p style="color: green"><%= notice %></p>
<%= turbo_frame_tag dom_id(@property) do %>
  <%= render @property %>
<% end %>
<div>
  <% if can? :update, @property %>
    <%= link_to "Edit this property", edit_property_path(@property), class:"btn btn-info" %> &nbsp&nbsp&nbsp&nbsp
  <%end%>
  <% if request.path== current_listings_properties_path %>
    <%= link_to "Back to properties", current_listings_properties_path , class:"btn btn-secondary" %>&nbsp&nbsp
  <% else %>   
    <%= link_to "Back to properties", root_path , class:"btn btn-secondary" %>&nbsp&nbsp
  <% end %>
  <% if can? :destroy,@property%>
    <%= button_to "Destroy this property", @property, method: :delete,class:"btn btn-danger"  %>
  <%end%>

</div>