config/routes.rb
Rails.application.routes.draw do
  root "properties#index"
  get "serch", to: "properties#profile"
  get "search", to: "properties#index"

  resources :properties do
    get :archive, on: :member
    get :approve_listing, on: :member
    collection do
      get :archived, action: :index
      get :pending_listings, action: :index
      get :unapproved_listings, action: :index
      get :current_listings, action: :index
      get :profile
    end
  end

  resources :users, only: :index do
    collection do
      get :main
      get :home
      get :about
      get :contact
    end
  end

  devise_for :users, controllers: { sessions: "sessions" }
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testproject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>
  <body style="background-color: powderblue;  ">
    <nav style="position: fixed;  top: 0; z-index: 1; width: 100%;" class="navbar navbar-expand-lg  navbar-dark bg-dark">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent" >
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            &nbsp<div class="dropdown">
              <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false" style="color:black">
                Property</a>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <li>
                     <%= link_to 'All properties', root_path, class: "dropdown-item",  class:"dropdown-item"%>
                  </li>
                  <% if user_signed_in? %>
                    <li><a class="dropdown-item"href="/properties/new">New property</a>
                    </li>
                  <% end %> 
                  <li>
                    <%= link_to 'Archieved properties', archived_properties_path, class: "dropdown-item", class:"dropdown-item"%>
                  </li>  
                </ul>
            </div>&nbsp&nbsp&nbsp&nbsp

            <li class="nav-item">
              <%= link_to 'About', about_users_path ,class:"navbar-brand"%>&nbsp&nbsp&nbsp
            </li>

            <li class="nav-item">
              <%= link_to 'Contact', contact_users_path ,class:"navbar-brand" %>&nbsp&nbsp&nbsp
            </li>
            
            <% if user_signed_in? %> 
              <li class="nav-item">
                <%= link_to 'Profile' , profile_properties_path ,class:"navbar-brand" %>
              </li>
              <li class="nav-item">
                <%= link_to "Logout", destroy_user_session_path, data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure to logout?"
                },class:"navbar-brand",style:"color:red" %> &nbsp&nbsp&nbsp      
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Sign up", new_user_registration_path ,class:"navbar-brand"  %>&nbsp&nbsp&nbsp
              </li>
              <%= link_to "Sign in",   new_user_session_path ,class:"navbar-brand"%><br />
            <% end %>

          </ul>
            <% if request.path==root_path || request.path==search_path %>
              <%= form_with url: "search", method: :get do |form| %>
                <%= form.label :q, "Search" %>
                <%= form.text_field :q , class:"form-control me-2", style:"position:absolute;right:100px;top:8px; width:250px",placeholder:"Search" %>
                <%= form.submit "Search",class:"btn btn-outline-success" %>
              <% end %>
            <%end%>
        </div>
      </div>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <p class="navbar-text float-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.<br>
        Are you Admin : <%=current_user.has_role? :admin %>
        <strong><%=current_user.roles.pluck(:name) %></strong>
      <% end %>
    </p>
   <% if request.path==profile_properties_path ||request.path == unapproved_listings_properties_path || request.path == current_listings_properties_path ||request.path==pending_listings_properties_path  %>
    <%=render 'profile' %>
   <% end %>
   <%= yield %>

  </body>
</html>